### ISSUE TITLE
Song list is blocking the audio controls

### ISSUE THREAD

**Issue by mitchelsevere** [KanteLabs/Music-Visualizer#1]
May need to have the song list div around 80vh and have the overflow scroll so it doesn't block the music player.

<img width="1429" alt="screen shot 2017-09-27 at 10 43 34" src="https://user-images.githubusercontent.com/17341609/30919989-e208f32e-a370-11e7-8f3b-93c3f3aef27a.png">

**Comment by KanteLabs** [comment]
Bug is fixed.
